import { useEffect, useState } from 'react';
import { customFetch } from '@workspace/api-client-react';
import { Mail, Save, RotateCcw, Eye } from 'lucide-react';
import { type EmailAppearance, type EmailTemplate } from '@workspace/vehicle-meta';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { NativeSelect } from '@/components/ui/native-select';
import './integration-settings.css';
type TemplateResponse = { revision: number; templates: EmailTemplate[]; variables: string[]; appearance: EmailAppearance; preview?: boolean };
type Preview = { subject: string; html: string; text: string };
const request = <T,>(path: string, method = 'GET', body?: unknown) => customFetch<T>(path, { method, ...(body ? { body: JSON.stringify(body), headers: { 'Content-Type': 'application/json' } } : {}) });
export function EmailTemplatesSettings() {
  const [data, setData] = useState<TemplateResponse>(), [selected, setSelected] = useState('enquiry_acknowledgement');
  const [subject, setSubject] = useState(''), [body, setBody] = useState(''), [preview, setPreview] = useState<Preview>();
  const [savedAppearance, setSavedAppearance] = useState('');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('');
  function apply(response: TemplateResponse, id = selected) { setData(response); const template = response.templates.find(item => item.id === id); if (template) { setSubject(template.subject); setBody(template.body); } setPreview(undefined); }
  async function load() { setBusy(true); setError(''); try { const result = await request<TemplateResponse>('/api/email-templates'); apply(result); setSavedAppearance(JSON.stringify(result.appearance)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The email templates could not be loaded.'); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  async function save(reset = false) { if (!data) return; setBusy(true); setError(''); setMessage(''); try { const result = await request<TemplateResponse>('/api/email-templates', 'PUT', { id: selected, expectedRevision: data.revision, ...(reset ? { reset: true } : { subject, body }) }); apply({ ...result, appearance: appearanceChanged ? data.appearance : result.appearance }); setMessage(reset ? 'Default email wording restored.' : 'Email template saved. Future emails will use this wording.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The template could not be saved.'); } finally { setBusy(false); } }
  async function saveAppearance() { if (!data) return; setBusy(true); setError(''); setMessage(''); try { const result = await request<TemplateResponse>('/api/email-templates/appearance', 'PUT', { expectedRevision: data.revision, appearance: data.appearance }); setData(result); setSavedAppearance(JSON.stringify(result.appearance)); setPreview(undefined); setMessage('Email branding saved for every email template.'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Email branding could not be saved.'); } finally { setBusy(false); } }
  async function showPreview() { setBusy(true); setError(''); try { setPreview(await request<Preview>(`/api/email-templates/${selected}/preview`, 'POST', { subject, body, appearance: data?.appearance })); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The preview could not be created.'); } finally { setBusy(false); } }
  function appearanceField(key: keyof EmailAppearance, value: string) { setData(current => current ? { ...current, appearance: { ...current.appearance, [key]: value } } : current); setPreview(undefined); }
  const active = data?.templates.find(template => template.id === selected);
  const appearanceChanged = Boolean(data && savedAppearance !== JSON.stringify(data.appearance));
  const wordingChanged = Boolean(active && (subject !== active.subject || body !== active.body));
  return <section className="integration-settings" aria-label="Customise all emails"><div className="integration-heading"><div><p className="integration-eyebrow">Customer communication</p><h2>Email templates</h2><p>Customise the subject and wording of every message. Variables fill in the customer and vehicle details automatically.</p></div><Mail aria-hidden="true" /></div>
    {error && <p role="alert" className="integration-error">{error}</p>}{message && <p role="status" className="integration-notice">{message}</p>}
    {!data ? <Button type="button" disabled={busy} onClick={() => void load()}>{busy ? 'Loading templates…' : 'Reload templates'}</Button> : <fieldset disabled={busy} className="min-w-0 space-y-5">
      <div className="integration-card"><h3>Branding for all emails</h3><div className="integration-grid"><div className="integration-field"><label htmlFor="email-logo">Logo image address</label><Input id="email-logo" type="url" value={data.appearance.logoUrl} onChange={event => appearanceField('logoUrl', event.target.value)} placeholder="https://yourdomain.co.uk/logo.png" /><small>Optional HTTPS image. Email apps may ask customers to load remote images.</small></div><div className="integration-field"><label htmlFor="email-colour">Brand colour</label><div className="email-colour-field"><input aria-label="Choose email brand colour" type="color" value={/^#[a-f0-9]{6}$/i.test(data.appearance.brandColour) ? data.appearance.brandColour : '#172033'} onChange={event => appearanceField('brandColour', event.target.value)} /><Input id="email-colour" value={data.appearance.brandColour} onChange={event => appearanceField('brandColour', event.target.value)} placeholder="#172033" maxLength={7} /></div></div><div className="integration-field"><label htmlFor="email-heading">Email heading</label><Input id="email-heading" value={data.appearance.heading} onChange={event => appearanceField('heading', event.target.value)} maxLength={200} /><small>Shown above every message. Variables are supported.</small></div><div className="integration-field"><label htmlFor="email-footer">Email footer</label><Textarea id="email-footer" rows={4} value={data.appearance.footer} onChange={event => appearanceField('footer', event.target.value)} maxLength={4000} placeholder="Your sign-off, contact details or company information" /><small>Shown after the confirmed details in every email. Variables are supported.</small></div></div><div><Button type="button" variant="outline" disabled={busy} onClick={() => void saveAppearance()}>Save email branding</Button></div></div>
      <div className="integration-field"><label htmlFor="email-template-select">Email to customise</label><NativeSelect id="email-template-select" value={selected} disabled={busy} onChange={event => { if (wordingChanged && !window.confirm('Discard the unsaved wording for this email?')) return; const id = event.target.value; setSelected(id); apply(data, id); setMessage(''); }}>{['Enquiries', 'Bookings', 'Reservations', 'Sales', 'Customer access'].map(category => <optgroup label={category} key={category}>{data.templates.filter(template => template.category === category).map(template => <option key={template.id} value={template.id}>{template.label}</option>)}</optgroup>)}</NativeSelect></div>
      <div className="email-template-grid"><div className="integration-card"><h3>{active?.label}</h3><div className="integration-field"><label htmlFor="email-subject">Subject</label><Input id="email-subject" maxLength={200} value={subject} onChange={event => { setSubject(event.target.value); setPreview(undefined); }} /></div><div className="integration-field"><label htmlFor="email-body">Message</label><Textarea id="email-body" rows={15} maxLength={12000} value={body} onChange={event => { setBody(event.target.value); setPreview(undefined); }} /><small>Plain text with variables. Line breaks are preserved. The dealership’s confirmed reference, appointment status and payment totals are added automatically below your message.</small></div><div className="integration-actions"><Button type="button" disabled={busy} onClick={() => void save()}><Save size={16} />Save template</Button><Button type="button" variant="outline" disabled={busy} onClick={() => void showPreview()}><Eye size={16} />Preview</Button><Button type="button" variant="ghost" disabled={busy} onClick={() => { if (window.confirm('Replace this email’s wording with the default and save it?')) void save(true); }}><RotateCcw size={16} />Restore default</Button></div></div>
      <aside className="integration-card"><h3>Available variables</h3><p>Click to add a variable to the message.</p><div className="email-variable-list">{data.variables.map(variable => <button type="button" key={variable} onClick={() => { setBody(current => `${current}${current.endsWith(' ') || current.endsWith('\n') ? '' : ' '}{{${variable}}}`); setPreview(undefined); }}>{`{{${variable}}}`}</button>)}</div><p className="integration-footnote">The preview uses sample information and sends no email. Confirmed payment and appointment details cannot be removed by editing the message.</p></aside></div>
      {preview && <div className="integration-card email-preview"><h3>Sample email preview</h3><p><strong>Subject:</strong> {preview.subject}</p><iframe title="Email preview using sample customer information" sandbox="" srcDoc={preview.html} /><p className="integration-footnote">Sample preview. No email has been sent.</p></div>}
      <Button type="button" variant="ghost" disabled={busy} onClick={() => { if ((!wordingChanged && !appearanceChanged) || window.confirm('Discard unsaved email wording and branding and reload?')) void load(); }}>Reload templates</Button>
    </fieldset>}
  </section>;
}
