import { useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { customFetch } from '@workspace/api-client-react';
import { Link, useSearch } from 'wouter';
import { Button } from '@/components/ui/button';
import { useDealerSettings } from '@/lib/dealer-settings-context';
type Payment = { reference: string; vehicleId: string; vehicleTitle: string; vehicleRegistration?: string; amountReceivedPence: number; depositPence: number; paymentStatus:string;status:string; mode:'test'|'live';needsReview:boolean };
export default function ReservationPaymentReturn() {
  const search = useSearch(); const params = new URLSearchParams(search); const reference = params.get('reference')??'', token = params.get('token')??'';
  const { settings } = useDealerSettings();
  useEffect(()=>{const meta=document.createElement('meta');meta.name='referrer';meta.content='no-referrer';document.head.appendChild(meta);return()=>meta.remove();},[]);
  const query = useQuery({ queryKey:['reservation-payment-status',reference,token],queryFn:()=>customFetch<{reservation:Payment}>('/api/reservations/payment-status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reference,token}),cache:'no-store',referrerPolicy:'no-referrer'}),enabled:!!reference&&!!token,retry:false,refetchInterval:query=>query.state.data?.reservation.paymentStatus==='pending'?15000:false });
  const record=query.data?.reservation; const paid=record?.mode==='live'&&record.paymentStatus==='confirmed'&&record.status==='reserved'; const test=record?.paymentStatus==='test_confirmed';
  return <main className="luxxy-shell px-4 py-12"><section className="luxxy-surface mx-auto max-w-xl rounded-xl border border-border p-6 sm:p-10"><p className="luxxy-kicker">Online reservation</p><h1 className="mt-4 font-display text-3xl font-semibold">{paid?'Your car is reserved':test?'Test payment completed':record?.status==='expired'?'Payment session expired':record?.status==='cancelled'?'Reservation cancelled':record&&record.paymentStatus.includes('refund')?'Your refund update':query.isError?'We couldn’t check your payment':record?'Payment confirmation pending':'Checking your reservation'}</h1>{!reference||!token?<p className="mt-4">This payment link is incomplete. Contact the showroom with your reservation reference.</p>:query.isError?<p role="alert" className="mt-4">Please contact the showroom with reference {reference}. Avoid making another payment until the team checks the status.</p>:!record?<p role="status" className="mt-4">Checking the confirmed payment status…</p>:<><p className="mt-4 font-semibold">{record.vehicleTitle} {record.vehicleRegistration&&`· ${record.vehicleRegistration}`}</p><p className="mt-2 font-mono">{record.reference}</p><p className="mt-4">{paid?`Your ${(record.amountReceivedPence/100).toLocaleString('en-GB',{style:'currency',currency:'GBP'})} deposit has been confirmed. The showroom will follow up with you.`:test?'No real money has been received. This test payment does not create a paid receipt.':record.status==='expired'?'No confirmed payment has been recorded. Return to the car to check current availability.':record.status==='cancelled'?'This payment session has been cancelled. Contact the showroom to check your reservation.':record.paymentStatus==='refunded'?'Your payment has been refunded. Contact the showroom for help.':record.paymentStatus==='partially_refunded'?'Part of your payment has been refunded. Contact the showroom for the remaining balance.':record.paymentStatus==='refund_pending'?'Your refund is being processed. It is recorded as returned only when Stripe confirms success.':record.paymentStatus==='refund_failed'?'The refund needs review. Contact the showroom with your reference.':'We are waiting for Stripe to confirm the payment. This page refreshes automatically. Please do not pay again.'}</p>{record.needsReview&&<p className="mt-4">The showroom needs to review the payment status before confirming the reservation.</p>}</>}<div className="mt-8 flex flex-wrap gap-3">{record&&<Button asChild><Link href={`/vehicle/${record.vehicleId}`}>View your car</Link></Button>}<Button asChild variant="outline"><Link href="/contact">Contact showroom</Link></Button>{query.isError&&<Button onClick={()=>void query.refetch()} variant="outline">Check again</Button>}</div><p className="mt-6 text-sm text-muted-foreground">{settings.identity.name}</p></section></main>;
}
