import { test, expect } from '@playwright/test';
test.skip(process.env.LUXXY_LOCAL_PREVIEW !== '1', 'Local preview; writes intercepted.');
for (const width of [390,820,1440]) test(`email and integration settings at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:1000});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/portal?section=settings');await page.getByRole('button',{name:'Email templates',exact:true}).click();await expect(page.getByRole('heading',{name:'Email templates',exact:true})).toBeVisible();const select=page.getByLabel('Email to customise');await expect.poll(()=>select.locator('option').count()).toBeGreaterThanOrEqual(16);await select.selectOption('payment_receipt');await expect(page.getByLabel('Subject',{exact:true})).toHaveValue(/Receipt/);await page.getByLabel('Subject',{exact:true}).fill('Receipt {{document_number}}');await page.getByLabel('Message',{exact:true}).fill('Thank you, {{customer_name}}.');await page.getByRole('button',{name:'Preview',exact:true}).click();await expect(page.frameLocator('iframe').getByText(/Thank you,/)).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:`/private/tmp/luxxy-email-settings-${width}.png`,fullPage:true});await page.getByRole('button',{name:'API integrations',exact:true}).click();await expect(page.getByRole('heading',{name:'API integrations',exact:true})).toBeVisible();await expect(page.getByLabel('API key',{exact:false})).toHaveValue('');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.getByRole('button',{name:'Publish history',exact:true}).click();await expect(page.getByRole('heading',{name:'Publication history'})).toBeVisible();expect(errors).toEqual([]);
});
test('template saves and rollback carry revision checks without provider calls',async({page})=>{
 let saved:any;await page.route('**/api/email-templates',async route=>{if(route.request().method()!=='PUT'){await route.continue();return;}saved=route.request().postDataJSON();const response=await route.fetch({method:'GET'});const data=await response.json();data.revision++;data.templates=data.templates.map((t:any)=>t.id===saved.id?{...t,subject:saved.subject,body:saved.body}:t);await route.fulfill({json:data});});await page.goto('/portal?section=settings');await page.getByRole('button',{name:'Email templates',exact:true}).click();await page.getByLabel('Email to customise').selectOption('invoice');await page.getByLabel('Subject',{exact:true}).fill('Invoice {{dealer_name}}');await page.getByRole('button',{name:'Save template',exact:true}).click();await expect(page.getByText('Email template saved. Future emails will use this wording.')).toBeVisible();expect(saved.expectedRevision).toBeGreaterThanOrEqual(0);expect(saved.id).toBe('invoice');await page.route('**/api/staff/settings-history',route=>route.fulfill({json:{revision:7,versions:[{revision:7,publishedAt:new Date().toISOString(),publishedBy:'Owner',action:'publish'},{revision:6,publishedAt:new Date().toISOString(),publishedBy:'Owner',action:'publish'}]}}));let revision:string|undefined;await page.route('**/api/staff/settings-history/6/restore',route=>{revision=route.request().headers()['if-match'];return route.fulfill({json:{revision:8}});});page.on('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'Publish history',exact:true}).click();await page.getByRole('button',{name:'Restore this version'}).click();await expect.poll(()=>revision).toBe('7');
});
test('overview links and source-enquiry sale action',async({page})=>{await page.goto('/portal?section=overview');await expect(page.getByRole('heading',{name:'Today at a glance'})).toBeVisible();await expect(page.getByRole('link',{name:'Open calendar'})).toHaveAttribute('href','/portal?section=test-drives');await page.getByTestId('tab-enquiries').click();await page.getByRole('tab',{name:'Find enquiry or appointment'}).click();await expect(page.getByRole('link',{name:'Start sale'}).first()).toHaveAttribute('href',/enquiryId=/);});

for (const [status,mode,received,title] of [['pending','live',0,'Payment confirmation pending'],['confirmed','live',10000,'Your car is reserved'],['test_confirmed','test',0,'Test payment completed'],['refund_pending','live',10000,'Your refund update']]) test(`payment return displays verified ${status} without trusting redirects`,async({page})=>{await page.setViewportSize({width:390,height:900});let input:any;await page.route('**/api/reservations/payment-status',route=>{input=route.request().postDataJSON();return route.fulfill({json:{reservation:{reference:'RSV-TEST',vehicleId:'fixture',vehicleTitle:'Fixture car',vehicleRegistration:'AB20 XYZ',amountReceivedPence:received,depositPence:10000,paymentStatus:status,status:'reserved',mode,needsReview:false}}});});await page.goto('/reserve/payment-return?reference=RSV-TEST&token='+'a'.repeat(64)+'&paid=true');await expect(page.getByRole('heading',{name:String(title),exact:true})).toBeVisible();expect(input.token).toBe('a'.repeat(64));if(status!=='confirmed')await expect(page.getByRole('heading',{name:'Your car is reserved'})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);});
