import { expect, test } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
test.skip(process.env.LUXXY_LOCAL_PREVIEW !== '1', 'Local fixtures only');
for (const width of [390, 1440]) {
  test(`used-car hero search and stock browsing at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 });
    await page.goto('/');
    const hero = page.getByRole('form', { name: 'Search used cars' });
    await expect(hero).toBeVisible();
    await expect(hero.getByRole('combobox', { name: 'Search model', exact: true })).toBeDisabled();
    await expect(page.getByTestId('showroom-hero-photo').locator('img')).toHaveJSProperty('complete', true);
    await expect(page.getByRole('button', { name: /^Search \d+ used cars$/ })).toBeVisible();
    await expect(hero).not.toContainText(/monthly|finance|new cars/i);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await mkdir('../../docs/screenshots/reference-homepage', { recursive: true });
    await page.screenshot({ path: `../../docs/screenshots/reference-homepage/hero-${width}.png` });
    await hero.getByRole('combobox', { name: 'Search make', exact: true }).selectOption('MG');
    await hero.getByRole('combobox', { name: 'Search model', exact: true }).selectOption('MG HS');
    await hero.getByRole('button', { name: 'Search 1 used car', exact: true }).click();
    await expect(page.locator('[data-testid^="card-vehicle-"]')).toHaveCount(1);
    await expect(page.getByTestId('card-vehicle-preview-2')).toBeVisible();
    await page.goto('/');
    await hero.getByRole('combobox', { name: 'Search make', exact: true }).selectOption('');
    await hero.getByRole('combobox', { name: 'Search maximum price', exact: true }).selectOption('5000');
    await hero.getByRole('button', { name: /^Search/ }).click();
    await expect(page.getByTestId('card-vehicle-preview-4')).toBeVisible();
    await page.getByTestId('button-view-all-stock').count();
    await page.goto('/');
    await hero.getByRole('combobox', { name: 'Search maximum price', exact: true }).selectOption('');
    await hero.getByText('Advanced options', { exact: true }).click();
    await hero.getByRole('combobox', { name: 'Search transmission', exact: true }).selectOption('Automatic');
    await hero.getByRole('button', { name: /^Search/ }).click();
    await expect(page.locator('[data-testid^="card-vehicle-"]').first()).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: `../../docs/screenshots/reference-homepage/stock-${width}.png` });
    const first = page.locator('[data-testid^="card-vehicle-"]').first();
    await first.getByRole('button', { name: /^Next photo/ }).click();
    await expect(first).toContainText('2 /');
    await first.getByRole('button', { name: /^Save .* to your saved cars/ }).click();
  });
}
