// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/luxxy/LuxxyConcierge.tsx": () => import("../components/mockups/luxxy/LuxxyConcierge.tsx"),
  "./components/mockups/luxxy/LuxxyLogoBoard.tsx": () => import("../components/mockups/luxxy/LuxxyLogoBoard.tsx")
};
